# automatisation de la création de l'index de commandes Linux

# utilisation de https://github.com/stefanzweifel/git-auto-commit-action
# voir aussi https://github.com/orgs/community/discussions/25640

name: linux commands index generation

on:
  push:
    branches: [ "main" ]

jobs:
  job_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show GCC version
        run: g++ --version

      - name: Determination type
        run: cd content/commands_csv; ./get_type.sh

      - name: Compilation
        run: cd content/commands_csv; g++ linux_gen.cpp
      - name: Exécution
        run: cd content/commands_csv; ./a.out out.csv

      - run: rm content/commands_csv/out.csv

      - name: Ajout version OS
        run: |
          source /etc/os-release;
          echo "_OS: $NAME - $VERSION_">> content/linux_cmds_list_alpha.md
          echo "_OS: $NAME - $VERSION_">> content/linux_cmds_list_cat.md
        

      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Automated Change
          branch: main
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true


