# plantuml gantt demo

name: linux commands index generation

on:
  push:
    branches: [ "main" ]

jobs:
  job_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show GCC version
        run: g++ --version
      - name: Run script
        run: cd content/commands_csv;./build.sh
      - run: echo "pwd:";pwd; echo "ls -R"; ls -R content
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_cds
          path: content/linux_*.md



