# plantuml gantt demo

name: plantuml_gantt_demo

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
# 20240614: ubuntu-latest install en fait Ubuntu22, et le
# parque correspondant pour plantum est la version... 2020!
# ... qui ne permet pas de compiler les fichiers
#      - name: Install plantuml
#        run: sudo apt-get -y install plantuml
      - name: Install plantuml from release
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2023.11/plantuml-1.2023.11.jar;cp plantuml-1.2023.11.jar /usr/local/bin/plantuml.jar
      - name: Show OS version
        run: lsb_release -a;pwd
#      - name: Show plantuml version
#        run: plantuml -version
      - name: Show java version
        run: java -version
      - name: Run script
        run: cd content/plantuml_gantt;./run.sh
      - run: echo "pwd:";pwd; echo "ls -R"; ls -R
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gant_2
          path: content/plantuml_gantt/gant_2.svg


#      - name: DL  
#        uses: actions/download-artifact@v4
#        with:
#          name: content/plantuml_gantt/out2/gantt_3.svg
#          path: /tmp
#      - name: Display structure of downloaded files
#       run: ls -R /tmp

